// Comprehensive list of popular emojis with emoji-toolkit compatible shortnames
// Based on the most commonly used emojis and matching Rocket.Chat's emoji autocomplete

const emojiList = [
  // Popular smileys and emotions
  { shortname: 'smile', emoji: '😊', aliases: ['happy', 'grinning'] },
  { shortname: 'laughing', emoji: '😂', aliases: ['joy', 'tears'] },
  { shortname: 'heart_eyes', emoji: '😍', aliases: ['love', 'heart'] },
  { shortname: 'kissing_heart', emoji: '😘', aliases: ['kiss', 'love'] },
  { shortname: 'wink', emoji: '😉', aliases: ['winking'] },
  { shortname: 'blush', emoji: '😊', aliases: ['smiling', 'happy'] },
  { shortname: 'grinning', emoji: '😀', aliases: ['grin', 'happy'] },
  { shortname: 'grin', emoji: '😁', aliases: ['grinning', 'happy'] },
  { shortname: 'joy', emoji: '😂', aliases: ['laughing', 'tears'] },
  { shortname: 'smiley', emoji: '😃', aliases: ['happy', 'grinning'] },
  { shortname: 'smirk', emoji: '😏', aliases: ['smirking'] },
  { shortname: 'relaxed', emoji: '☺️', aliases: ['smile', 'happy'] },
  {
    shortname: 'stuck_out_tongue',
    emoji: '😛',
    aliases: ['tongue', 'playful'],
  },
  {
    shortname: 'stuck_out_tongue_winking_eye',
    emoji: '😜',
    aliases: ['wink', 'tongue'],
  },
  {
    shortname: 'stuck_out_tongue_closed_eyes',
    emoji: '😝',
    aliases: ['tongue', 'playful'],
  },
  { shortname: 'kissing', emoji: '😗', aliases: ['kiss'] },
  {
    shortname: 'kissing_smiling_eyes',
    emoji: '😙',
    aliases: ['kiss', 'happy'],
  },
  { shortname: 'kissing_closed_eyes', emoji: '😚', aliases: ['kiss', 'love'] },
  { shortname: 'yum', emoji: '😋', aliases: ['delicious', 'tasty'] },
  { shortname: 'relieved', emoji: '😌', aliases: ['relief', 'sigh'] },
  { shortname: 'hugs', emoji: '🤗', aliases: ['hugging'] },
  { shortname: 'thinking', emoji: '🤔', aliases: ['thought', 'considering'] },
  { shortname: 'neutral_face', emoji: '😐', aliases: ['neutral', 'meh'] },
  { shortname: 'expressionless', emoji: '😑', aliases: ['blank', 'neutral'] },
  { shortname: 'no_mouth', emoji: '😶', aliases: ['mute', 'silent'] },
  { shortname: 'rolling_eyes', emoji: '🙄', aliases: ['eyeroll', 'sarcasm'] },
  { shortname: 'smiling_imp', emoji: '😈', aliases: ['devil', 'evil'] },
  { shortname: 'imp', emoji: '👿', aliases: ['devil', 'evil'] },
  { shortname: 'japanese_ogre', emoji: '👹', aliases: ['monster', 'ogre'] },
  { shortname: 'japanese_goblin', emoji: '👺', aliases: ['goblin', 'monster'] },
  { shortname: 'skull', emoji: '💀', aliases: ['death', 'dead'] },
  { shortname: 'ghost', emoji: '👻', aliases: ['spooky', 'halloween'] },
  { shortname: 'alien', emoji: '👽', aliases: ['ufo', 'extraterrestrial'] },
  { shortname: 'robot', emoji: '🤖', aliases: ['bot', 'automation'] },
  { shortname: 'smiley_cat', emoji: '😸', aliases: ['cat', 'happy'] },
  { shortname: 'smile_cat', emoji: '😹', aliases: ['cat', 'laughing'] },
  { shortname: 'joy_cat', emoji: '😻', aliases: ['cat', 'love'] },
  { shortname: 'heart_eyes_cat', emoji: '😻', aliases: ['cat', 'love'] },
  { shortname: 'smirk_cat', emoji: '😼', aliases: ['cat', 'smirk'] },
  { shortname: 'kissing_cat', emoji: '😽', aliases: ['cat', 'kiss'] },
  { shortname: 'scream_cat', emoji: '🙀', aliases: ['cat', 'scared'] },
  { shortname: 'crying_cat_face', emoji: '😿', aliases: ['cat', 'cry', 'sad'] },
  { shortname: 'pouting_cat', emoji: '😾', aliases: ['cat', 'angry'] },

  // Hand gestures
  { shortname: 'thumbsup', emoji: '👍', aliases: ['yes', 'good', 'approve'] },
  {
    shortname: 'thumbsdown',
    emoji: '👎',
    aliases: ['no', 'bad', 'disapprove'],
  },
  { shortname: 'clap', emoji: '👏', aliases: ['applause', 'bravo'] },
  { shortname: 'open_hands', emoji: '👐', aliases: ['open', 'hands'] },
  { shortname: 'palms_up_together', emoji: '🤲', aliases: ['prayer', 'hands'] },
  { shortname: 'handshake', emoji: '🤝', aliases: ['deal', 'agreement'] },
  { shortname: 'pray', emoji: '🙏', aliases: ['please', 'thanks', 'hope'] },
  { shortname: 'writing_hand', emoji: '✍️', aliases: ['write', 'signature'] },
  { shortname: 'nail_care', emoji: '💅', aliases: ['nail', 'polish'] },
  { shortname: 'selfie', emoji: '🤳', aliases: ['camera', 'photo'] },
  { shortname: 'muscle', emoji: '💪', aliases: ['strong', 'flex', 'biceps'] },
  { shortname: 'mechanical_arm', emoji: '🦾', aliases: ['arm', 'robot'] },
  { shortname: 'mechanical_leg', emoji: '🦿', aliases: ['leg', 'robot'] },
  { shortname: 'leg', emoji: '🦵', aliases: ['kick', 'limb'] },
  { shortname: 'foot', emoji: '🦶', aliases: ['kick', 'limb'] },
  { shortname: 'ear', emoji: '👂', aliases: ['listen', 'hear'] },
  {
    shortname: 'ear_with_hearing_aid',
    emoji: '🦻',
    aliases: ['hearing', 'aid'],
  },
  { shortname: 'nose', emoji: '👃', aliases: ['smell', 'sniff'] },
  { shortname: 'brain', emoji: '🧠', aliases: ['think', 'smart'] },
  { shortname: 'anatomical_heart', emoji: '🫀', aliases: ['heart', 'health'] },
  { shortname: 'lungs', emoji: '🫁', aliases: ['breath', 'health'] },
  { shortname: 'tooth', emoji: '🦷', aliases: ['dental', 'health'] },
  { shortname: 'bone', emoji: '🦴', aliases: ['skeleton', 'health'] },
  { shortname: 'eyes', emoji: '👀', aliases: ['see', 'look', 'watch'] },
  { shortname: 'eye', emoji: '👁️', aliases: ['see', 'look'] },
  { shortname: 'tongue', emoji: '👅', aliases: ['taste', 'lick'] },
  { shortname: 'lips', emoji: '👄', aliases: ['kiss', 'mouth'] },

  // Hearts and symbols
  { shortname: 'heart', emoji: '❤️', aliases: ['love', 'red'] },
  { shortname: 'orange_heart', emoji: '🧡', aliases: ['love', 'orange'] },
  { shortname: 'yellow_heart', emoji: '💛', aliases: ['love', 'yellow'] },
  { shortname: 'green_heart', emoji: '💚', aliases: ['love', 'green'] },
  { shortname: 'blue_heart', emoji: '💙', aliases: ['love', 'blue'] },
  { shortname: 'purple_heart', emoji: '💜', aliases: ['love', 'purple'] },
  { shortname: 'black_heart', emoji: '🖤', aliases: ['love', 'black'] },
  { shortname: 'white_heart', emoji: '🤍', aliases: ['love', 'white'] },
  { shortname: 'brown_heart', emoji: '🤎', aliases: ['love', 'brown'] },
  { shortname: 'broken_heart', emoji: '💔', aliases: ['sad', 'broken'] },
  {
    shortname: 'heart_exclamation',
    emoji: '❣️',
    aliases: ['love', 'exclamation'],
  },
  { shortname: 'two_hearts', emoji: '💕', aliases: ['love', 'two'] },
  {
    shortname: 'revolving_hearts',
    emoji: '💞',
    aliases: ['love', 'revolving'],
  },
  { shortname: 'heartbeat', emoji: '💓', aliases: ['love', 'beat'] },
  { shortname: 'heartpulse', emoji: '💗', aliases: ['love', 'pulse'] },
  { shortname: 'heart_eyes', emoji: '😍', aliases: ['love', 'heart'] },
  { shortname: 'sparkling_heart', emoji: '💖', aliases: ['love', 'sparkle'] },
  { shortname: 'cupid', emoji: '💘', aliases: ['love', 'arrow'] },
  { shortname: 'gift_heart', emoji: '💝', aliases: ['love', 'gift'] },
  {
    shortname: 'heart_decoration',
    emoji: '💟',
    aliases: ['love', 'decoration'],
  },
  { shortname: 'peace_symbol', emoji: '☮️', aliases: ['peace', 'symbol'] },
  { shortname: 'latin_cross', emoji: '✝️', aliases: ['cross', 'christian'] },
  { shortname: 'star_and_crescent', emoji: '☪️', aliases: ['islam', 'muslim'] },
  { shortname: 'om', emoji: '🕉️', aliases: ['hindu', 'om'] },
  {
    shortname: 'wheel_of_dharma',
    emoji: '☸️',
    aliases: ['buddhism', 'dharma'],
  },
  { shortname: 'star_of_david', emoji: '✡️', aliases: ['judaism', 'star'] },
  { shortname: 'six_pointed_star', emoji: '🔯', aliases: ['star', 'jewish'] },
  { shortname: 'menorah', emoji: '🕎', aliases: ['hanukkah', 'candles'] },
  { shortname: 'yin_yang', emoji: '☯️', aliases: ['balance', 'tao'] },
  { shortname: 'orthodox_cross', emoji: '☦️', aliases: ['christian', 'cross'] },
  {
    shortname: 'place_of_worship',
    emoji: '🛐',
    aliases: ['worship', 'religion'],
  },
  { shortname: 'ophiuchus', emoji: '⛎', aliases: ['snake', 'zodiac'] },
  { shortname: 'aries', emoji: '♈', aliases: ['ram', 'zodiac'] },
  { shortname: 'taurus', emoji: '♉', aliases: ['bull', 'zodiac'] },
  { shortname: 'gemini', emoji: '♊', aliases: ['twins', 'zodiac'] },
  { shortname: 'cancer', emoji: '♋', aliases: ['crab', 'zodiac'] },
  { shortname: 'leo', emoji: '♌', aliases: ['lion', 'zodiac'] },
  { shortname: 'virgo', emoji: '♍', aliases: ['maiden', 'zodiac'] },
  { shortname: 'libra', emoji: '♎', aliases: ['scales', 'zodiac'] },
  { shortname: 'scorpius', emoji: '♏', aliases: ['scorpion', 'zodiac'] },
  { shortname: 'sagittarius', emoji: '♐', aliases: ['archer', 'zodiac'] },
  { shortname: 'capricorn', emoji: '♑', aliases: ['goat', 'zodiac'] },
  { shortname: 'aquarius', emoji: '♒', aliases: ['water', 'zodiac'] },
  { shortname: 'pisces', emoji: '♓', aliases: ['fish', 'zodiac'] },
  { shortname: 'id', emoji: '🆔', aliases: ['identification', 'id'] },
  { shortname: 'atom_symbol', emoji: '⚛️', aliases: ['atom', 'science'] },
  { shortname: 'u7a7a', emoji: '🈳', aliases: ['japanese', 'empty'] },
  { shortname: 'u5272', emoji: '🈹', aliases: ['japanese', 'discount'] },
  {
    shortname: 'radioactive',
    emoji: '☢️',
    aliases: ['nuclear', 'radioactive'],
  },
  { shortname: 'biohazard', emoji: '☣️', aliases: ['danger', 'biohazard'] },
  { shortname: 'mobile_phone_off', emoji: '📴', aliases: ['off', 'phone'] },
  { shortname: 'vibration_mode', emoji: '📳', aliases: ['vibrate', 'phone'] },
  { shortname: 'u6709', emoji: '🈶', aliases: ['japanese', 'available'] },
  { shortname: 'u7121', emoji: '🈚', aliases: ['japanese', 'not'] },
  { shortname: 'u7533', emoji: '🈸', aliases: ['japanese', 'application'] },
  { shortname: 'u55b6', emoji: '🈺', aliases: ['japanese', 'open'] },
  { shortname: 'u6708', emoji: '🈷️', aliases: ['japanese', 'monthly'] },
  {
    shortname: 'eight_pointed_black_star',
    emoji: '✴️',
    aliases: ['star', 'eight'],
  },
  { shortname: 'vs', emoji: '🆚', aliases: ['versus', 'vs'] },
  { shortname: 'accept', emoji: '🉑', aliases: ['japanese', 'acceptable'] },
  { shortname: 'white_flower', emoji: '💮', aliases: ['flower', 'white'] },
  {
    shortname: 'ideograph_advantage',
    emoji: '🉐',
    aliases: ['japanese', 'advantage'],
  },
  { shortname: 'secret', emoji: '㊙️', aliases: ['japanese', 'secret'] },
  {
    shortname: 'congratulations',
    emoji: '㊗️',
    aliases: ['japanese', 'congratulations'],
  },
  { shortname: 'u5408', emoji: '🈴', aliases: ['japanese', 'congratulation'] },
  { shortname: 'u6e80', emoji: '🈵', aliases: ['japanese', 'full'] },
  { shortname: 'u7981', emoji: '🈲', aliases: ['japanese', 'prohibited'] },
  { shortname: 'a', emoji: '🅰️', aliases: ['blood', 'type'] },
  { shortname: 'b', emoji: '🅱️', aliases: ['blood', 'type'] },
  { shortname: 'ab', emoji: '🆎', aliases: ['blood', 'type'] },
  { shortname: 'cl', emoji: '🆑', aliases: ['clear', 'clear'] },
  { shortname: 'o2', emoji: '🅾️', aliases: ['blood', 'type'] },
  { shortname: 'sos', emoji: '🆘', aliases: ['help', 'emergency'] },
  { shortname: 'no_entry', emoji: '⛔', aliases: ['no', 'entry'] },
  { shortname: 'name_badge', emoji: '📛', aliases: ['name', 'badge'] },
  { shortname: 'no_entry_sign', emoji: '🚫', aliases: ['no', 'entry'] },
  { shortname: 'x', emoji: '❌', aliases: ['no', 'cross'] },
  { shortname: 'o', emoji: '⭕', aliases: ['yes', 'circle'] },
  { shortname: 'stop_sign', emoji: '🛑', aliases: ['stop', 'sign'] },
  { shortname: 'anger', emoji: '💢', aliases: ['angry', 'mad'] },
  { shortname: 'hotsprings', emoji: '♨️', aliases: ['hot', 'springs'] },
  { shortname: 'no_pedestrians', emoji: '🚷', aliases: ['no', 'pedestrians'] },
  { shortname: 'do_not_litter', emoji: '🚯', aliases: ['no', 'litter'] },
  { shortname: 'no_bicycles', emoji: '🚳', aliases: ['no', 'bicycles'] },
  { shortname: 'non-potable_water', emoji: '🚱', aliases: ['no', 'water'] },
  { shortname: 'underage', emoji: '🔞', aliases: ['underage', '18'] },
  { shortname: 'no_mobile_phones', emoji: '📵', aliases: ['no', 'phone'] },
  {
    shortname: 'exclamation',
    emoji: '❗',
    aliases: ['exclamation', 'warning'],
  },
  {
    shortname: 'grey_exclamation',
    emoji: '❕',
    aliases: ['exclamation', 'grey'],
  },
  { shortname: 'question', emoji: '❓', aliases: ['question', 'help'] },
  { shortname: 'grey_question', emoji: '❔', aliases: ['question', 'grey'] },
  { shortname: 'bangbang', emoji: '‼️', aliases: ['exclamation', 'double'] },
  {
    shortname: 'interrobang',
    emoji: '⁉️',
    aliases: ['exclamation', 'question'],
  },
  { shortname: '100', emoji: '💯', aliases: ['hundred', 'perfect'] },
  { shortname: 'low_brightness', emoji: '🔅', aliases: ['dim', 'brightness'] },
  {
    shortname: 'high_brightness',
    emoji: '🔆',
    aliases: ['bright', 'brightness'],
  },
  { shortname: 'trident', emoji: '🔱', aliases: ['trident', 'fork'] },
  { shortname: 'fleur_de_lis', emoji: '⚜️', aliases: ['fleur', 'lily'] },
  {
    shortname: 'part_alternation_mark',
    emoji: '〽️',
    aliases: ['japanese', 'part'],
  },
  { shortname: 'warning', emoji: '⚠️', aliases: ['warning', 'caution'] },
  {
    shortname: 'children_crossing',
    emoji: '🚸',
    aliases: ['children', 'crossing'],
  },
  { shortname: 'beginner', emoji: '🔰', aliases: ['beginner', 'leaf'] },
  { shortname: 'recycle', emoji: '♻️', aliases: ['recycle', 'green'] },
  { shortname: 'u6307', emoji: '🈯', aliases: ['japanese', 'point'] },
  { shortname: 'chart', emoji: '💹', aliases: ['chart', 'yen'] },
  { shortname: 'sparkle', emoji: '✨', aliases: ['sparkle', 'shine'] },
  {
    shortname: 'eight_spoked_asterisk',
    emoji: '✳️',
    aliases: ['asterisk', 'eight'],
  },
  {
    shortname: 'negative_squared_cross_mark',
    emoji: '❎',
    aliases: ['no', 'cross'],
  },
  { shortname: 'white_check_mark', emoji: '✅', aliases: ['yes', 'check'] },
  {
    shortname: 'diamond_shape_with_a_dot_inside',
    emoji: '💠',
    aliases: ['diamond', 'dot'],
  },
  { shortname: 'cyclone', emoji: '🌀', aliases: ['cyclone', 'spiral'] },
  { shortname: 'loop', emoji: '➿', aliases: ['loop', 'curly'] },
  {
    shortname: 'globe_with_meridians',
    emoji: '🌐',
    aliases: ['globe', 'world'],
  },
  { shortname: 'm', emoji: 'Ⓜ️', aliases: ['metro', 'm'] },
  { shortname: 'atm', emoji: '🏧', aliases: ['atm', 'cash'] },
  { shortname: 'sa', emoji: '🈂️', aliases: ['japanese', 'service'] },
  {
    shortname: 'passport_control',
    emoji: '🛂',
    aliases: ['passport', 'control'],
  },
  { shortname: 'customs', emoji: '🛃', aliases: ['customs', 'border'] },
  { shortname: 'baggage_claim', emoji: '🛄', aliases: ['baggage', 'claim'] },
  { shortname: 'left_luggage', emoji: '🛅', aliases: ['left', 'luggage'] },
  {
    shortname: 'wheelchair',
    emoji: '♿',
    aliases: ['wheelchair', 'accessibility'],
  },
  { shortname: 'no_smoking', emoji: '🚭', aliases: ['no', 'smoking'] },
  { shortname: 'wc', emoji: '🚾', aliases: ['toilet', 'wc'] },
  { shortname: 'parking', emoji: '🅿️', aliases: ['parking', 'p'] },
  { shortname: 'potable_water', emoji: '🚰', aliases: ['water', 'drinking'] },
  { shortname: 'mens', emoji: '🚹', aliases: ['men', 'male'] },
  { shortname: 'womens', emoji: '🚺', aliases: ['women', 'female'] },
  { shortname: 'baby_symbol', emoji: '🚼', aliases: ['baby', 'symbol'] },
  { shortname: 'restroom', emoji: '🚻', aliases: ['restroom', 'toilet'] },
  {
    shortname: 'put_litter_in_its_place',
    emoji: '🚮',
    aliases: ['litter', 'bin'],
  },
  { shortname: 'cinema', emoji: '🎦', aliases: ['cinema', 'movie'] },
  {
    shortname: 'signal_strength',
    emoji: '📶',
    aliases: ['signal', 'strength'],
  },
  { shortname: 'koko', emoji: '🈁', aliases: ['japanese', 'here'] },
  { shortname: 'ng', emoji: '🆖', aliases: ['ng', 'no'] },
  { shortname: 'ok', emoji: '🆗', aliases: ['ok', 'okay'] },
  { shortname: 'up', emoji: '🆙', aliases: ['up', 'arrow'] },
  { shortname: 'cool', emoji: '🆒', aliases: ['cool', 'fresh'] },
  { shortname: 'new', emoji: '🆕', aliases: ['new', 'fresh'] },
  { shortname: 'free', emoji: '🆓', aliases: ['free', 'complimentary'] },
  { shortname: 'zero', emoji: '0️⃣', aliases: ['zero', '0'] },
  { shortname: 'one', emoji: '1️⃣', aliases: ['one', '1'] },
  { shortname: 'two', emoji: '2️⃣', aliases: ['two', '2'] },
  { shortname: 'three', emoji: '3️⃣', aliases: ['three', '3'] },
  { shortname: 'four', emoji: '4️⃣', aliases: ['four', '4'] },
  { shortname: 'five', emoji: '5️⃣', aliases: ['five', '5'] },
  { shortname: 'six', emoji: '6️⃣', aliases: ['six', '6'] },
  { shortname: 'seven', emoji: '7️⃣', aliases: ['seven', '7'] },
  { shortname: 'eight', emoji: '8️⃣', aliases: ['eight', '8'] },
  { shortname: 'nine', emoji: '9️⃣', aliases: ['nine', '9'] },
  { shortname: 'keycap_ten', emoji: '🔟', aliases: ['ten', '10'] },

  // Additional popular emojis
  { shortname: 'fire', emoji: '🔥', aliases: ['hot', 'flame'] },
  { shortname: 'boom', emoji: '💥', aliases: ['explosion', 'bang'] },
  { shortname: 'collision', emoji: '💥', aliases: ['explosion', 'bang'] },
  { shortname: 'sweat_drops', emoji: '💦', aliases: ['water', 'drops'] },
  { shortname: 'droplet', emoji: '💧', aliases: ['water', 'drop'] },
  { shortname: 'dash', emoji: '💨', aliases: ['wind', 'fast'] },
  { shortname: 'hole', emoji: '🕳️', aliases: ['hole', 'dark'] },
  { shortname: 'bomb', emoji: '💣', aliases: ['bomb', 'explosive'] },
  { shortname: 'speech_balloon', emoji: '💬', aliases: ['speech', 'bubble'] },
  { shortname: 'eye_speech_bubble', emoji: '👁️‍🗨️', aliases: ['eye', 'speech'] },
  { shortname: 'left_speech_bubble', emoji: '🗨️', aliases: ['left', 'speech'] },
  { shortname: 'right_anger_bubble', emoji: '🗯️', aliases: ['right', 'anger'] },
  { shortname: 'thought_balloon', emoji: '💭', aliases: ['thought', 'bubble'] },
  { shortname: 'zzz', emoji: '💤', aliases: ['sleep', 'tired'] },
  { shortname: 'wave', emoji: '👋', aliases: ['hello', 'goodbye'] },
  { shortname: 'raised_back_of_hand', emoji: '🤚', aliases: ['stop', 'hand'] },
  {
    shortname: 'raised_hand_with_fingers_splayed',
    emoji: '🖐️',
    aliases: ['stop', 'hand'],
  },
  { shortname: 'hand', emoji: '✋', aliases: ['stop', 'hand'] },
  { shortname: 'spock-hand', emoji: '🖖', aliases: ['spock', 'vulcan'] },
  { shortname: 'the_horns', emoji: '🤘', aliases: ['rock', 'metal'] },
  { shortname: 'call_me_hand', emoji: '🤙', aliases: ['call', 'phone'] },
  { shortname: 'point_left', emoji: '👈', aliases: ['left', 'point'] },
  { shortname: 'point_right', emoji: '👉', aliases: ['right', 'point'] },
  { shortname: 'point_up_2', emoji: '👆', aliases: ['up', 'point'] },
  { shortname: 'middle_finger', emoji: '🖕', aliases: ['middle', 'finger'] },
  { shortname: 'point_down', emoji: '👇', aliases: ['down', 'point'] },
  { shortname: 'point_up', emoji: '☝️', aliases: ['up', 'point'] },
  { shortname: 'point_up_2', emoji: '👆', aliases: ['up', 'point'] },
  { shortname: 'crossed_fingers', emoji: '🤞', aliases: ['luck', 'cross'] },
  { shortname: 'love_you_gesture', emoji: '🤟', aliases: ['love', 'you'] },
  { shortname: 'metal', emoji: '🤘', aliases: ['rock', 'metal'] },
  { shortname: 'vulcan_salute', emoji: '🖖', aliases: ['spock', 'vulcan'] },
  {
    shortname: 'index_pointing_at_the_viewer',
    emoji: '🫵',
    aliases: ['point', 'you'],
  },
  { shortname: 'palms_up_together', emoji: '🤲', aliases: ['prayer', 'hands'] },
  { shortname: 'back_of_hand', emoji: '🤚', aliases: ['back', 'hand'] },
  {
    shortname: 'hand_with_index_finger_and_thumb_crossed',
    emoji: '🤌',
    aliases: ['pinch', 'money'],
  },
  { shortname: 'index_pointing_up', emoji: '☝️', aliases: ['up', 'point'] },
  {
    shortname: 'index_pointing_at_the_viewer_dark_skin_tone',
    emoji: '🫵🏿',
    aliases: ['point', 'you', 'dark'],
  },
  {
    shortname: 'index_pointing_at_the_viewer_light_skin_tone',
    emoji: '🫵🏻',
    aliases: ['point', 'you', 'light'],
  },
  {
    shortname: 'index_pointing_at_the_viewer_medium_dark_skin_tone',
    emoji: '🫵🏾',
    aliases: ['point', 'you', 'medium_dark'],
  },
  {
    shortname: 'index_pointing_at_the_viewer_medium_light_skin_tone',
    emoji: '🫵🏼',
    aliases: ['point', 'you', 'medium_light'],
  },
  {
    shortname: 'index_pointing_at_the_viewer_medium_skin_tone',
    emoji: '🫵🏽',
    aliases: ['point', 'you', 'medium'],
  },
  { shortname: 'thumbs_up', emoji: '👍', aliases: ['yes', 'good', 'approve'] },
  {
    shortname: 'thumbs_down',
    emoji: '👎',
    aliases: ['no', 'bad', 'disapprove'],
  },
  { shortname: 'raised_fist', emoji: '✊', aliases: ['fist', 'punch'] },
  { shortname: 'oncoming_fist', emoji: '👊', aliases: ['fist', 'punch'] },
  { shortname: 'left_facing_fist', emoji: '🤛', aliases: ['fist', 'left'] },
  { shortname: 'right_facing_fist', emoji: '🤜', aliases: ['fist', 'right'] },
  { shortname: 'clap', emoji: '👏', aliases: ['applause', 'bravo'] },
  { shortname: 'raised_hands', emoji: '🙌', aliases: ['celebration', 'hands'] },
  { shortname: 'open_hands', emoji: '👐', aliases: ['open', 'hands'] },
  { shortname: 'palms_up_together', emoji: '🤲', aliases: ['prayer', 'hands'] },
  { shortname: 'handshake', emoji: '🤝', aliases: ['deal', 'agreement'] },
  { shortname: 'pray', emoji: '🙏', aliases: ['please', 'thanks', 'hope'] },
  { shortname: 'writing_hand', emoji: '✍️', aliases: ['write', 'signature'] },
  { shortname: 'nail_care', emoji: '💅', aliases: ['nail', 'polish'] },
  { shortname: 'selfie', emoji: '🤳', aliases: ['camera', 'photo'] },
  { shortname: 'muscle', emoji: '💪', aliases: ['strong', 'flex', 'biceps'] },
  { shortname: 'mechanical_arm', emoji: '🦾', aliases: ['arm', 'robot'] },
  { shortname: 'mechanical_leg', emoji: '🦿', aliases: ['leg', 'robot'] },
  { shortname: 'leg', emoji: '🦵', aliases: ['kick', 'limb'] },
  { shortname: 'foot', emoji: '🦶', aliases: ['kick', 'limb'] },
  { shortname: 'ear', emoji: '👂', aliases: ['listen', 'hear'] },
  {
    shortname: 'ear_with_hearing_aid',
    emoji: '🦻',
    aliases: ['hearing', 'aid'],
  },
  { shortname: 'nose', emoji: '👃', aliases: ['smell', 'sniff'] },
  { shortname: 'brain', emoji: '🧠', aliases: ['think', 'smart'] },
  { shortname: 'anatomical_heart', emoji: '🫀', aliases: ['heart', 'health'] },
  { shortname: 'lungs', emoji: '🫁', aliases: ['breath', 'health'] },
  { shortname: 'tooth', emoji: '🦷', aliases: ['dental', 'health'] },
  { shortname: 'bone', emoji: '🦴', aliases: ['skeleton', 'health'] },
  { shortname: 'eyes', emoji: '👀', aliases: ['see', 'look', 'watch'] },
  { shortname: 'eye', emoji: '👁️', aliases: ['see', 'look'] },
  { shortname: 'tongue', emoji: '👅', aliases: ['taste', 'lick'] },
  { shortname: 'lips', emoji: '👄', aliases: ['kiss', 'mouth'] },
];

export default emojiList;
