tasks:
  - name: Initialize RC server
    init: |
      docker-compose up -d
  - name: Initialize playground
    init: |
      npm install
      cd playground 
      npm install
      cd ..
    command: npm run dev
