name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

env:
  STORYBOOK_RC_HOST: 'https://demo.qa.rocket.chat'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.19.0"

      - name: Build and publish Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn install
          build_command: yarn build && yarn build:storybook
          path: packages/react/storybook-static
          checkout: false
