name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

env: 
  STORYBOOK_RC_HOST: "https://demo.qa.rocket.chat"
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.19.0"

      - name: Install Dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build:storybook
        working-directory: packages/react

      - name: Build UI-Elements
        run: yarn build:storybook
        working-directory: packages/ui-elements

      - name: Prepare Build Folder
        run: |
          mkdir -p build
          mkdir -p build/ui-elements
          mv -v packages/react/storybook-static/* build/
          mv -v packages/ui-elements/storybook-static/* build/ui-elements/

      - name: 'Upload Storybook Artifacts'
        uses: actions/upload-pages-artifact@v3
        with: 
          path: build
    
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
